default:
    host:   "cluster0.npgfdeg.mongodb.net"
    username:   "despinola"
    password:   "francais2"

production:
    host:   "cluster0.npgfdeg.mongodb.net"
    username:   "despinola"
    password:   "francais2"